<?php

namespace Database\Seeders;

use App\Models\Color;
use Illuminate\Database\Seeder;

class ColorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $colors = [
            ['name' => 'BLANCO', 'code' => '001'],
            ['name' => 'NEGRO', 'code' => '002'],
            ['name' => 'VERDE', 'code' => '003'],
            ['name' => 'FUCSIA', 'code' => '004'],
            ['name' => 'TURQUEZA', 'code' => '005'],
            ['name' => 'ROSADO', 'code' => '006'],
            ['name' => 'AMARILLO', 'code' => '007'],
            ['name' => 'ANARANJADO', 'code' => '008'],
            ['name' => 'IVORY', 'code' => '009'],
            ['name' => 'CELESTE', 'code' => '010'],
            ['name' => 'BEIGE', 'code' => '011'],
            ['name' => 'MGE', 'code' => '012'],
            ['name' => 'MGE C/CELESTE', 'code' => '013'],
            ['name' => 'NEGRO C/ MGE', 'code' => '014'],
            ['name' => 'ROJO', 'code' => '015'],
            ['name' => 'IVO/ROSADO', 'code' => '016'],
            ['name' => 'IVO/CELESTE', 'code' => '017'],
            ['name' => 'VINO', 'code' => '018'],
            ['name' => 'PALO ROSA', 'code' => '019'],
            ['name' => 'VARIOS', 'code' => '020'],
            ['name' => 'LACRE', 'code' => '021'],
            ['name' => 'AQUA', 'code' => '022'],
            ['name' => 'CHICLE', 'code' => '023'],
            ['name' => 'VERDE LIMON', 'code' => '024'],
            ['name' => 'MANDARINA', 'code' => '025'],
            ['name' => 'MARRON', 'code' => '026'],
            ['name' => 'MELON', 'code' => '027'],
            ['name' => 'BLANCO MAN', 'code' => '028'],
            ['name' => 'BCO-AQUA', 'code' => '030'],
            ['name' => 'BCO-ROSADO', 'code' => '031'],
            ['name' => 'BCO-CHICLE', 'code' => '032'],
            ['name' => 'BCO-VERDE LIMON', 'code' => '033'],
            ['name' => 'COBALTO', 'code' => '034'],
            ['name' => 'BARNEY', 'code' => '035'],
            ['name' => 'VERDE MILITAR', 'code' => '036'],
            ['name' => 'BICOLOR', 'code' => '037'],
            ['name' => 'CAFE', 'code' => '038'],
            ['name' => 'MARFIL', 'code' => '040'],
            ['name' => 'CELESTE-MARR', 'code' => '041'],
            ['name' => 'CEMENTO-VER', 'code' => '042'],
            ['name' => 'COCOA-LAD', 'code' => '043'],
            ['name' => 'NUEZ', 'code' => '044'],
            ['name' => 'MORO', 'code' => '045'],
            ['name' => 'COCOA', 'code' => '046'],
            ['name' => 'UVA', 'code' => '047'],
            ['name' => 'BCO-NEGRO', 'code' => '048'],
            ['name' => 'BLANCO-VERDE', 'code' => '049'],
            ['name' => 'BCO-MANDARINA', 'code' => '050'],
            ['name' => 'BLANCO-UVA', 'code' => '051'],
            ['name' => 'BCO-COBALTO', 'code' => '052'],
            ['name' => 'BCO-FUCSIA', 'code' => '053'],
            ['name' => 'MORADO', 'code' => '054'],
            ['name' => 'AQUA-MANDARINA', 'code' => '055'],
            ['name' => 'MORADO-VERDE LIMON', 'code' => '056'],
            ['name' => 'NGR-CHICLE', 'code' => '058'],
            ['name' => 'FUCSIA-NEGRO', 'code' => '059'],
            ['name' => 'NGR-FUCSIA', 'code' => '060'],
            ['name' => 'GRIS OSCURO', 'code' => '061'],
            ['name' => 'VERDE LIMON-MORADO', 'code' => '062'],
            ['name' => 'LAVANDA', 'code' => '063'],
            ['name' => 'FRESA', 'code' => '064'],
            ['name' => 'AGUA MARINA', 'code' => '065'],
            ['name' => 'BCO-TURQUEZA', 'code' => '066'],
            ['name' => 'ACERO', 'code' => '067'],
            ['name' => 'PLOMO GRIS', 'code' => '068'],
            ['name' => 'ARENA', 'code' => '069'],
            ['name' => 'BLANCO E', 'code' => '070'],
            ['name' => 'LAVANDA-MORADO', 'code' => '071'],
            ['name' => 'NEG-AGUA M', 'code' => '072'],
            ['name' => 'VERDE LIMON-ACERO', 'code' => '073'],
            ['name' => 'BCO-LAVANDA', 'code' => '074'],
            ['name' => 'BCO-FRESA', 'code' => '075'],
            ['name' => 'BCO-AGUA MARINA', 'code' => '076'],
            ['name' => 'BCO-BARNEY', 'code' => '078'],
            ['name' => 'NEGRO-ROJO', 'code' => '079'],
            ['name' => 'FRESA-IVORY', 'code' => '080'],
            ['name' => 'AGUA MARINA-NGR', 'code' => '081'],
            ['name' => 'CORAL', 'code' => '082'],
            ['name' => 'NGR-AGUA MARINA', 'code' => '083'],
            ['name' => 'NG-AGUA MARINA', 'code' => '084'],
            ['name' => 'BCO-MORADO', 'code' => '085'],
            ['name' => 'FRESA-BLANCO', 'code' => '086'],
            ['name' => 'BCO-ÑUSTA', 'code' => '087'],
            ['name' => 'NEGRO-ÑUSTA', 'code' => '088'],
            ['name' => 'LAVANDA-ÑUSTA', 'code' => '089'],
            ['name' => 'FRESA-ÑUSTA', 'code' => '090'],
            ['name' => 'MORADO-ÑUSTA', 'code' => '091'],
            ['name' => 'BCO-LLAMA', 'code' => '092'],
            ['name' => 'FRESA-LLAMA', 'code' => '093'],
            ['name' => 'NEGRO-LLAMA', 'code' => '094'],
            ['name' => 'AGUA MARINA-LLAMA', 'code' => '095'],
            ['name' => 'NEGRO-BLANCO', 'code' => '096'],
            ['name' => 'FUCSIA-BCO', 'code' => '097'],
            ['name' => 'NEGRO-FRESA', 'code' => '098'],
            ['name' => 'MORADO-LILA', 'code' => '099'],
            ['name' => 'CORAL-NEGRO', 'code' => '100'],
            ['name' => 'GRIS OSCURO-AGUA MARINA', 'code' => '101'],
            ['name' => 'CORAL-BLANCO', 'code' => '102'],
            ['name' => 'LILA', 'code' => '103'],
            ['name' => 'BCO-ACERO', 'code' => '104'],
            ['name' => 'BLANCO INST', 'code' => '105'],
            ['name' => 'NEGRO INST', 'code' => '106'],
            ['name' => 'ACERO OSCURO', 'code' => '107'],
            ['name' => 'BEIGE CARNE', 'code' => '108'],
            ['name' => 'ACERO E', 'code' => '109'],
            ['name' => 'LILA E', 'code' => '110'],
            ['name' => 'AGUA MARINA E', 'code' => '111'],
            ['name' => 'FRESA E', 'code' => '112'],
            ['name' => 'IVORY-LAVANDA', 'code' => '113'],
            ['name' => 'COCOA GALIA', 'code' => '114'],
            ['name' => 'VERDE CLARISA', 'code' => '115'],
            ['name' => 'TURQUEZA-BLANCO', 'code' => '116'],
            ['name' => 'ROJO-VERDE LIMON', 'code' => '117'],
            ['name' => 'PLOMO OSCURO', 'code' => '118'],
            ['name' => 'NEGRO-PLOMO', 'code' => '119'],
            ['name' => 'AZUL MARINO-VERDE LIMON', 'code' => '120'],
            ['name' => 'BEIGE 1', 'code' => '121'],
            ['name' => 'BEIGE 2', 'code' => '122'],
            ['name' => 'BEIGE 3', 'code' => '123'],
            ['name' => 'BEIGE 4', 'code' => '124'],
            ['name' => 'IVORI 1', 'code' => '125'],
            ['name' => 'IVORI 2', 'code' => '126'],
            ['name' => 'IVORI 3', 'code' => '127'],
            ['name' => 'IVORI 4', 'code' => '128'],
            ['name' => 'IVORI 5', 'code' => '129'],
            ['name' => 'FUCCIA CLARISA', 'code' => '130'],
            ['name' => 'VERDE CEMENTO', 'code' => '131'],
            ['name' => 'GUINDA', 'code' => '132'],
            ['name' => 'LADRILLO OSCURO', 'code' => '133'],
            ['name' => 'MARRON CLARO', 'code' => '134'],
            ['name' => 'LADRILLO', 'code' => '135'],
            ['name' => 'COCOA ABRIL', 'code' => '136'],
            ['name' => 'COCOA LADRILLO', 'code' => '137'],
            ['name' => 'BLANCO-NARANJA', 'code' => '138'],
            ['name' => 'ÑUSTA MORADO', 'code' => '139'],
            ['name' => 'ÑUSTA NEGRO', 'code' => '140'],
            ['name' => 'ÑUSTA FRESA', 'code' => '141'],
            ['name' => 'LLAMA NEGRO', 'code' => '142'],
            ['name' => 'LLAMA FRESA', 'code' => '143'],
            ['name' => 'LLAMA AGUA MARINA', 'code' => '144'],
            ['name' => 'PLOMO', 'code' => '145'],
            ['name' => 'GRIS', 'code' => '146'],
            ['name' => 'VERDE OSCURO', 'code' => '147'],
            ['name' => 'DLIRIO', 'code' => '148'],
            ['name' => 'NIQUELADA', 'code' => '149'],
            ['name' => 'CREMA', 'code' => '150'],
            ['name' => 'BEIGE-NEGRO', 'code' => '151'],
            ['name' => 'BEIGE-MARRON', 'code' => '152'],
            ['name' => 'IVORY-LILA', 'code' => '153'],
            ['name' => 'TRANSPARENTE', 'code' => '154'],
            ['name' => 'CHOCOLATE', 'code' => '155'],
            ['name' => 'LILA ROJIZO', 'code' => '156'],
            ['name' => 'BLANCO-MORADO', 'code' => '157'],
            ['name' => 'PLATEADO', 'code' => '158'],
            ['name' => 'AZUL', 'code' => '159'],
            ['name' => 'ROSADO BEBE', 'code' => '160'],
            ['name' => 'BLANCO-FRESA ÑUSTA', 'code' => '161'],
            ['name' => 'PERLA', 'code' => '162'],
            ['name' => 'ROJO-VERDE', 'code' => '163'],
            ['name' => 'NEGRO-VERDE', 'code' => '164'],
            ['name' => 'DORADO', 'code' => '165'],
            ['name' => 'LILA-UVA', 'code' => '166'],
            ['name' => 'AZULINO', 'code' => '167'],
            ['name' => 'VIOLETA', 'code' => '168'],
            ['name' => 'AZUL MARINO', 'code' => '169'],
            ['name' => 'PLOMO PIZARRA', 'code' => '170'],
            ['name' => 'CONCHO VINO', 'code' => '171'],
            ['name' => 'MARRON-MANDARINA', 'code' => '172'],
            ['name' => 'BARNEY-BCO', 'code' => '173'],
            ['name' => 'NGR-TURQUEZA', 'code' => '174'],
            ['name' => 'ROSADO-MARRON', 'code' => '175'],
            ['name' => 'MORADO-VERDE', 'code' => '176'],
            ['name' => 'MARRON-CHICLE', 'code' => '177'],
            ['name' => 'CRUDO', 'code' => '178'],
            ['name' => 'BEIGE CLARO', 'code' => '179'],
            ['name' => 'BCO-CORAL', 'code' => '180'],
            ['name' => 'LAVANDA-LILA', 'code' => '181'],
            ['name' => 'BCO-LILA', 'code' => '182'],
            ['name' => 'CORAL-MARRON', 'code' => '183'],
            ['name' => 'CHICLE-LILA', 'code' => '184'],
            ['name' => 'NARANJA', 'code' => '185'],
            ['name' => 'GRIS OSCURO ELECTRICO', 'code' => '186'],
            ['name' => 'ELECTRICO', 'code' => '187'],
            ['name' => 'GRIS OSCURO-FUCSIA', 'code' => '188'],
            ['name' => 'BLANCO-AZULINO', 'code' => '189'],
            ['name' => 'MELANGE', 'code' => '190'],
            ['name' => 'ROSADO BALLENA', 'code' => '191'],
            ['name' => 'LIMA', 'code' => '192'],
            ['name' => 'SALVIA', 'code' => '193'],
            ['name' => 'CASTANHO', 'code' => '194'],
            ['name' => 'AZUL ELECTRICO', 'code' => '195'],
            ['name' => 'ROSADO-AGUA MARINA', 'code' => '196'],
            ['name' => 'ROSADO-LILA', 'code' => '197'],
            ['name' => 'VERDE FOSFORESCENTE', 'code' => '198'],
            ['name' => 'VITAMIN', 'code' => '199'],
            ['name' => 'AZUL FUERTE', 'code' => '200'],
            ['name' => 'VIRTUAL PINK', 'code' => '201'],
            ['name' => 'PETUNIA', 'code' => '202'],
            ['name' => 'NGRO-AMARILLO', 'code' => '203'],
            ['name' => 'CELESTE-BCO', 'code' => '204'],
            ['name' => 'ROJO-AMARILLO', 'code' => '205'],
            ['name' => 'AZUL-FUCSIA', 'code' => '206'],
            ['name' => 'FUCSIA NEON', 'code' => '207'],
            ['name' => 'SANDIA', 'code' => '208'],
            ['name' => 'ROJO-NEGRO', 'code' => '209'],
            ['name' => 'AZULINO-FUCSIA', 'code' => '210'],
            ['name' => 'COCORAL', 'code' => '211'],
            ['name' => 'VAINILLA', 'code' => '212'],
            ['name' => 'UVA-IVORY', 'code' => '213'],
            ['name' => 'NEGRO-VERDE LIMON', 'code' => '214'],
            ['name' => 'COCOA-SANDIA', 'code' => '215'],
            ['name' => 'BLANCO-AMARILLO NEON', 'code' => '216'],
            ['name' => 'NEGRO-SANDIA NEON', 'code' => '217'],
            ['name' => 'AZULINO-AZULINO NEON', 'code' => '218'],
            ['name' => 'VAINILLA-PERLA NEON', 'code' => '219'],
            ['name' => 'TURQUEZA-NEGRO', 'code' => '220'],
            ['name' => 'MARRON-CORAL', 'code' => '221'],
            ['name' => 'AZUL ROYAL', 'code' => '222'],
            ['name' => 'SANDIA-NGRO', 'code' => '223'],
            ['name' => 'CORAL- NEGRO NEON', 'code' => '224'],
            ['name' => 'VIOLETA NEON', 'code' => '225'],
            ['name' => 'AZUL NEON', 'code' => '226'],
            ['name' => 'NARANJA NEON', 'code' => '227'],
            ['name' => 'AZUL-AMARILLO', 'code' => '228'],
            ['name' => 'GRIS-NEGRO', 'code' => '229'],
            ['name' => 'AZUL ROYAL-FUCSIA', 'code' => '230'],
            ['name' => 'BLANCO-FRESA LLAMA', 'code' => '231'],
            ['name' => 'TURQUEZA-AQUA', 'code' => '232'],
            ['name' => 'FUCSIA-CHICLE', 'code' => '233'],
            ['name' => 'LILA-LAVANDA', 'code' => '234'],
            ['name' => 'VERDE BB-CHICLE', 'code' => '235'],
            ['name' => 'MELON-VERDE BB', 'code' => '236'],
            ['name' => 'ZAMAC', 'code' => '237'],
            ['name' => 'LILA NEON', 'code' => '238'],
            ['name' => 'VERDE LIMON NEON', 'code' => '239'],
            ['name' => 'CORAL NEON', 'code' => '240'],
            ['name' => 'NEGRO-SANDIA', 'code' => '241'],
            ['name' => 'CONCHEVINO', 'code' => '242'],
            ['name' => 'MELON-AQUA', 'code' => '243'],
            ['name' => 'ATLANTIS', 'code' => '244'],
            ['name' => 'AZUL MEDIEVAL', 'code' => '245'],
            ['name' => 'CONCHO VINO-ROSE', 'code' => '246'],
            ['name' => 'AZUL OSCURO', 'code' => '247'],
            ['name' => 'BEIGE NATURAL', 'code' => '248'],
            ['name' => 'ROSE', 'code' => '249'],
            ['name' => 'MANDARINA-BCO', 'code' => '250'],
            ['name' => 'BCO-GRIS', 'code' => '251'],
            ['name' => 'COCOA-CORAL', 'code' => '252'],
            ['name' => 'PETUNIA-BLUE', 'code' => '253'],
            ['name' => 'FUCSIA-LATEX', 'code' => '254'],
            ['name' => 'AZUL MARINO-LATEX', 'code' => '255'],
            ['name' => 'AMARILLO-VERDE LIMON', 'code' => '256'],
            ['name' => 'BLANCO TOMATO', 'code' => '257'],
            ['name' => 'BLANCO PINK', 'code' => '258'],
            ['name' => 'BLANCO BLUE', 'code' => '259'],
            ['name' => 'BLANCO AQUA GREEN', 'code' => '260'],
            ['name' => 'VERDE BB', 'code' => '261'],
            ['name' => 'TURQUEZA-AZUL', 'code' => '262'],
            ['name' => 'BLANCO RED', 'code' => '263'],
            ['name' => 'IVORY-DORADO', 'code' => '264'],
            ['name' => 'FUCSIA-DORADO', 'code' => '265'],
            ['name' => 'AZUL-DORADO', 'code' => '266'],
            ['name' => 'VERDIPRO-NEGRO', 'code' => '267'],
            ['name' => 'VERDIPRO-ROJO', 'code' => '268'],
            ['name' => 'VERDIPRO-CHICLE', 'code' => '269'],
            ['name' => 'AMARILLO NEON', 'code' => '270'],
            ['name' => 'PINK', 'code' => '271'],
            ['name' => 'BLUE', 'code' => '272'],
            ['name' => 'AQUA GREEN', 'code' => '273'],
            ['name' => 'FUCSIA-PETUNIA', 'code' => '274'],
            ['name' => 'VIOLETA-PURPURA', 'code' => '275'],
            ['name' => 'INDIGO', 'code' => '276'],
            ['name' => 'MELANCH-AGUA MARINA', 'code' => '277'],
            ['name' => 'ROSADO-CHICLE', 'code' => '278'],
            ['name' => 'VERDE BB-LILA', 'code' => '279'],
            ['name' => 'VERDE LIMON-LILA', 'code' => '280'],
            ['name' => 'CONCHEVINO-INDIGO', 'code' => '281'],
            ['name' => 'VIOLETA PURPURA-LILA', 'code' => '282'],
            ['name' => 'CONCHE VINO', 'code' => '283'],
            ['name' => 'TURQUEZA-AZUL MEDIEVAL', 'code' => '284'],
            ['name' => 'VERDE PERICO', 'code' => '285'],
            ['name' => 'BLANCO/BCO', 'code' => '286'],
            ['name' => 'CEREZA', 'code' => '287'],
            ['name' => 'GRIS OSCURO-ATLANTIS', 'code' => '288'],
            ['name' => 'CHIFON', 'code' => '289'],
            ['name' => 'BEIGE-PACIFIC', 'code' => '290'],
            ['name' => 'ROJO-PACIFIC', 'code' => '291'],
            ['name' => 'TURQUEZA-PLATA', 'code' => '292'],
            ['name' => 'TURQUEZA-VERDE FOSFORESCENTE', 'code' => '293'],
            ['name' => 'MORO-LADRILLO', 'code' => '294'],
            ['name' => 'PLATA', 'code' => '295'],
            ['name' => 'COBALTO-VERDE LIMON', 'code' => '296'],
            ['name' => 'LILA BEBE', 'code' => '297'],
            ['name' => 'VERDE MANZANA', 'code' => '298'],
            ['name' => 'FUCSIA CLARO', 'code' => '299'],
            ['name' => 'MAGENTA', 'code' => '300'],
            ['name' => 'MELANGE APACHE', 'code' => '301'],
            ['name' => 'MELANGE AQUA', 'code' => '302'],
            ['name' => 'MELANGE MELON', 'code' => '303'],
            ['name' => 'MELANGE GERANIO', 'code' => '304'],
            ['name' => 'AZUL/MAGENTA', 'code' => '305'],
            ['name' => 'NEGRO/SANDIA', 'code' => '306'],
            ['name' => 'AZUL MARINO/MELON', 'code' => '307'],
            ['name' => 'ROJO/BLANCO', 'code' => '308'],
            ['name' => 'ROJO MEDIEVAL', 'code' => '309'],
            ['name' => 'MENTA', 'code' => '310'],
            ['name' => 'GERANIO', 'code' => '311'],
            ['name' => 'GRIS/VERDE ESMERALDA', 'code' => '312'],
            ['name' => 'ROJO VINO', 'code' => '313'],
            ['name' => 'RED MEDIEVAL', 'code' => '314'],
            ['name' => 'CELESTE CIELO', 'code' => '315'],
            ['name' => 'PINK TAFFY', 'code' => '316'],
            ['name' => 'GRIS/TURQUEZA', 'code' => '317'],
            ['name' => 'PLATA/TURQUEZA', 'code' => '318'],
            ['name' => 'PLATA/BLANCO', 'code' => '319'],
            ['name' => 'PLATA/NEGRO', 'code' => '321'],
            ['name' => 'VERDE AGUA', 'code' => '323'],
            ['name' => 'SALMON', 'code' => '324'],
            ['name' => 'TURQUEZA BEBE', 'code' => '325'],
            ['name' => 'ACERO MELANGE', 'code' => '326'],
            ['name' => 'AZUL JEANS', 'code' => '327'],
            ['name' => 'NEGRO CON BLANCO', 'code' => '328'],
            ['name' => 'AZUL MARINO CON CORAL', 'code' => '329'],
            ['name' => 'PLATA/ROJO', 'code' => '330'],
            ['name' => 'PLATA/AZUL MEDIEVAL', 'code' => '331'],
            ['name' => 'DORADO/BEIGE NATURAL', 'code' => '332'],
            ['name' => 'AZUL REY', 'code' => '333'],
            ['name' => 'GRIS-COBALTO', 'code' => '334'],
            ['name' => 'ROSADO RED', 'code' => '335'],
            ['name' => 'PLOMO PLATA', 'code' => '336'],
            ['name' => 'ROSADO CLARO', 'code' => '337'],
            ['name' => 'SEMI-BLANCO', 'code' => '338'],
            ['name' => 'VERDE ESMERALDA', 'code' => '339'],
            ['name' => 'MELON BB', 'code' => '340'],
            ['name' => 'AMARILLO PASTEL', 'code' => '341'],
            ['name' => 'LAVANDA PASTEL', 'code' => '342'],
            ['name' => 'MENTA PASTEL', 'code' => '343'],
            ['name' => 'ROSADO PASTEL', 'code' => '344'],
            ['name' => 'ESMERALDA', 'code' => '345'],
            ['name' => 'HOT PINK', 'code' => '346'],
            ['name' => 'PALO ROSA NIÑAS', 'code' => '347'],
            ['name' => 'BCO-CELESTE', 'code' => '348'],
            ['name' => 'BCO-ROJO', 'code' => '349'],
            ['name' => 'BCO-VERDE', 'code' => '350'],
            ['name' => 'PLATA/VINO', 'code' => '351'],
            ['name' => 'PLATA/MELANGE', 'code' => '352'],
            ['name' => 'VINO-IVORY', 'code' => '353'],
            ['name' => 'MARRON-IVORY', 'code' => '354'],
            ['name' => 'VERDE MILITAR-IVORY', 'code' => '355'],
            ['name' => 'BCO-SANDIA', 'code' => '356'],
            ['name' => 'BCO-ESMERALDA', 'code' => '357'],
            ['name' => 'VERDE JADE', 'code' => '358'],
            ['name' => 'PLOMO-BLANCO', 'code' => '359'],
            ['name' => 'ROSADO - BLANCO', 'code' => '360'],
            ['name' => 'VERDE AG - BLANCO', 'code' => '361'],
            ['name' => 'IVORY - BLANCO', 'code' => '362'],
            ['name' => 'ROSADO-NEGRO', 'code' => '363'],
            ['name' => 'VERDE AG-NEGRO', 'code' => '364'],
            ['name' => 'IVORY-NEGRO', 'code' => '365'],
            ['name' => 'CHICLE-BLANCO', 'code' => '366'],
            ['name' => 'LILA-BLANCO', 'code' => '367'],
            ['name' => 'MELON-BLANCO', 'code' => '368'],
            ['name' => 'AZUL MEDIEVAL / FRESA', 'code' => '369'],
            ['name' => 'MELANGE /FRESA', 'code' => '370'],
            ['name' => 'MOSTAZA', 'code' => '371'],
            ['name' => 'OCRE ORO', 'code' => '372'],
            ['name' => 'PUERTO AZUL', 'code' => '373'],
            ['name' => 'MORA', 'code' => '374'],
            ['name' => 'ORANGE', 'code' => '375'],
            ['name' => 'DARK GRAY', 'code' => '376'],
            ['name' => 'BLACK', 'code' => '377'],
            ['name' => 'WHITE', 'code' => '378'],
            ['name' => 'NEGRO/CALAVERA', 'code' => '379'],
            ['name' => 'BLANCO /GATO', 'code' => '380'],
            ['name' => 'AZUL/LETRAS', 'code' => '381'],
            ['name' => 'CUADROS', 'code' => '382'],
            ['name' => 'AZUL-PLOMO', 'code' => '383'],
            ['name' => 'BLANCO UV', 'code' => '384'],
        ];

        foreach ($colors as $color) {
            Color::create([
                'name' => $color['name'],
                'code' => $color['code']
            ]);
        }
    }
}
